### ISSUE TITLE
ImportError: No module named biplist

### ISSUE THREAD

**Issue by elalemanyo** [idolpx/iOSDump#1]
Hi,
I am trying to use your code to get some stuff from an old iOS backup, but I am getting this error:

```
Traceback (most recent call last):
  File "iosdumpui.py", line 10, in <module>
    from ios import ios
  File "/www/iOSDump/ios.py", line 26, in <module>
    from biplist import *
ImportError: No module named biplist
```

Any Idea what I am doing wrong?

Thanks!

**Comment by elalemanyo** [comment]
ok, sorry it was a local problem.

Thanks for your tool!

**Comment by tweinreich** [comment]
I had the same problem and noticed the following:

- It doesn't work if you use `pip install biplist`
- It worked for me using `python -m pip install biplist`

Just wanted to add this for future reference as @elalemanyo didn't explain how he fixed it.
