### ISSUE TITLE
Add requirements file to repository 

### ISSUE THREAD

**Issue by tweinreich** [idolpx/iOSDump#2]
Hey @idolpx - first of all thank you for sharing this with the rest of us.

While trying run iOSDump I stumbled across multiple ImportErrors. To prevent this in the future you could add a requirements file that contains:
- kivy
- biplist
- pygame
 
BTW: I got it running on Linux by installing the mentioned modules and creating the folders `~/Projects/python/iOSDump` and `~/Library/Application Support/MobileSync/Backup`.

**Comment by idolpx** [comment]
Thanks!  Sorry so slow to reply.  I haven't checked back here in a while.

**Comment by tweinreich** [comment]
You're welcome & no problem.
