### ISSUE TITLE
iTunes Backup API

### ISSUE THREAD

**Issue by tristarforensics** [idolpx/iOSDump#3]
Hello, love the project. I am trying to do something similar, except instead of processing the already dumped iTunes backup, I want to incorporate the actual iTunes backup functionality into my Python script, and backup the phone with my program. After this, I will process the backup similar to your program. I have been looking for an iTunes API for python to do this, but everything I've found has just been to interact with the iTunes web store. Have you come across anything like this in your development of this program?

**Comment by idolpx** [comment]
I haven't.  I would be curious to know about what you find (have found). 
Sorry so slow to reply.  I haven't checked in on this project in a while.
