### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by MoDerPo** [idolpx/iOSDump#4]
```
python iosdumpui.py
```
```
python iosdumpui.py
  File "C:\Users\____\Downloads\iOSDump-master\iosdumpui.py", line 136
    print "Dumping " + str(iosBackup.index)
          ^
SyntaxError: invalid syntax
```

**Comment by MoDerPo** [comment]
is this python 2?

**Comment by idolpx** [comment]
Yes... it was when I wrote it.  :)
Could use some updating.

**Comment by MoDerPo** [comment]
Ah I see. I could do a pr if you want I have some time on my hand

**Comment by idolpx** [comment]
Sure!  Any contributions are welcome.

**Comment by idolpx** [comment]
Looks like some of that work has been done here.  https://github.com/eirism/iOSDump

**Comment by idolpx** [comment]
I did a few quick changes and pushed them.  Still needs testing.
Probably more work too.

**Comment by MoDerPo** [comment]
it also looks like it's using an old module maybe?

**Comment by MoDerPo** [comment]
two actually

**Comment by MoDerPo** [comment]
ModuleNotFoundError: No module named 'biplist'

**Comment by idolpx** [comment]
I was able to install "biplist".  Just do "pip3 install biplist".  That should install it.
